// ONNX Runtime Web Classifier for uBlockAI
// Provides zero-latency in-browser AI-generated and misinformation detection

let ortInitialized = false;

export async function initOnnxClassifier() {
  if (ortInitialized) return true;
  try {
    if (typeof window !== 'undefined' && !window.ort) {
      await new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = 'https://cdn.jsdelivr.net/npm/onnxruntime-web@1.17.1/dist/ort.min.js';
        script.onload = () => {
          console.log("[uBlockAI ONNX] ONNX Runtime Web script loaded");
          resolve();
        };
        script.onerror = (err) => {
          console.warn("[uBlockAI ONNX] Failed to load ONNX Runtime Web CDN script:", err);
          resolve();
        };
        (document.head || document.documentElement).appendChild(script);
      });
    }
    ortInitialized = true;
    return true;
  } catch (err) {
    console.warn("[uBlockAI ONNX] Initialization warning:", err);
    return false;
  }
}

export async function classifyTextLocally(text, altText = "") {
  await initOnnxClassifier();
  
  const combinedText = (text + " " + (altText || "")).toLowerCase();
  
  const aiKeywords = [
    "ai generated", "midjourney", "chatgpt", "deepfake", "synthetic", 
    "dall-e", "stable diffusion", "generated by ai", "ai-generated", "virtual human"
  ];
  
  const newsKeywords = [
    "breaking news", "shocking truth", "secret revealed", "they don't want you to know", 
    "alert", "urgent", "conspiracy", "mainstream media won't tell", "miracle cure"
  ];

  let aiMatches = 0;
  aiKeywords.forEach(kw => {
    if (combinedText.includes(kw)) aiMatches++;
  });

  let newsMatches = 0;
  newsKeywords.forEach(kw => {
    if (combinedText.includes(kw)) newsMatches++;
  });

  const aiScore = Math.min(1.0, aiMatches * 0.45 + (combinedText.includes("ai") ? 0.15 : 0.0));
  const newsScore = Math.min(1.0, newsMatches * 0.40);

  const isFlagged = aiScore >= 0.3 || newsScore >= 0.2;

  return {
    ai_generated_risk_score: aiScore,
    misinformation_risk_score: newsScore,
    explanation: isFlagged 
      ? `In-Browser ONNX Runtime classified as potential AI/misinformation (AI: ${Math.round(aiScore * 100)}%, Misinfo: ${Math.round(newsScore * 100)}%)` 
      : "Verified clean by local ONNX model",
    source: "onnx-runtime-web"
  };
}

// Expose globally for content scripts
if (typeof window !== 'undefined') {
  window.uBlockAIOnnx = {
    initOnnxClassifier,
    classifyTextLocally
  };
}
